### ISSUE TITLE
Example for implementation to Project

### ISSUE THREAD

**Issue by NexusMTO** [watson-developer-cloud/speech-to-text-websockets-ruby#7]
Hello how to implement to Project with microphone?

**Comment by daniel-bolanos** [comment]
Hello @zephiro , I have not tried to capture audio from the microphone myself using Ruby (this project is really about showing how to interact with the Watson STT service). If you need to capture from microphone rather than pushing audio from a file, you can search online. This is one promising link I just found: http://stackoverflow.com/questions/20473556/ruby-gem-for-microphone-and-speaker

btw. When you get it to work you might want to integrate the mic feature into this project.

**Comment by Unstop-M** [comment]
Thanks!  I work with link
